---

# Swap

- name: Disable swap
  shell: "swapoff -a"

- name: Disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

# Kernel module

- name: Set containerd kernel module # for persist accross system reboot
  lineinfile:
    create: yes
    path: /etc/modules-load.d/containerd.conf
    line: "{{ item }}"
  loop:
    "{{ kernel_module }}"

- name: Add Kernel module
  modprobe:
    name: "{{ item }}"
  loop:
    "{{ kernel_module }}"

# Network configuration

- name: Copy sysctl network kubernetes configuration # for persist accros system reboot
  copy:
    src: sysctl-kubernetes.conf
    dest: /etc/sysctl.d/kubernetes-network.conf

- name: Reload sysctl --system
  shell: "sysctl --system"

# DNS resolution

- name: Insert a line at the end of /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }} {{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}"
  with_inventory_hostnames:
    - cluster

- name: "Set DNS resolver /etc/netplan/01-netcfg.yaml"
  template:
    src: 01-netcfg.yml.j2
    dest: /etc/netplan/01-netcfg.yaml

- name: "Set DNS resolver /etc/systemd/resolved.conf"
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf

- name: Restart systemd-resolved daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: systemd-resolved

- name: reload netplan
  shell: netplan apply

# Install package

# Add Google cloud repository to access kubernetes package
- name: Add kubernetes APT GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubernetes APT repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: 'kubernetes.list'

# add Docker repository to access lastest version of containerd.io
- name: Add docker APT GPG key                                    
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker APT repository
  apt_repository:  
    repo: "deb https://download.docker.com/linux/ubuntu focal stable"
    state: present
    filename: 'docker.list'

- name: Update apt package
  apt:
    update_cache: yes

- name: Install packages
  apt:
    allow_downgrade: yes
    name: "{{ item }}"
  loop:
    "{{ packages }}"

# Setup config & restart containerd daemon

- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Generate containerd config
  shell: "containerd config default | sudo tee /etc/containerd/config.toml"

- name: Enable and start containerd daemon
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
    enabled: yes

