---

- name: Install kubernetes pip
  pip:
    name:
      - pyyaml
      - kubernetes 

- name: Download pod network manifest
  get_url:
    url: "{{ pod_network_manifest }}"
    dest: /tmp/pod_network_manifest.yaml

- name: Deploy pod network
  k8s:
    state: present
    src: /tmp/pod_network_manifest.yaml

