---

- hosts: cluster                            # run on all host
  become: yes
  gather_facts: yes
  roles:
    - { role: node-configuration }

- hosts: master[0]                          # run only in master1
  become: yes
  gather_facts: yes
  roles:
    - { role: kubeadm-init }
    - { role: kube-user } 
    - { role: cni }

- hosts: cluster,!master[0]                 # run on all host except master1
  become: yes
  roles:
    - { role: kubeadm-join } 

